# Generated by Django 4.2 on 2025-04-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultydetails',
            fields=[
                ('facultyid', models.IntegerField(primary_key=True, serialize=False)),
                ('facultyname', models.CharField(max_length=100)),
                ('facultyage', models.IntegerField()),
                ('facultyresearch', models.TextField()),
            ],
        ),
    ]
