# Generated by Django 4.2 on 2025-04-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awarddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nominationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=100)),
                ('awardtype', models.CharField(max_length=100)),
            ],
        ),
    ]
